# Generated by Django 5.0.3 on 2024-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='required_intake',
        ),
    ]
