# Generated by Django 5.0.3 on 2024-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_customuser_required_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='required_intake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
