# Generated by Django 5.0.7 on 2024-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='created',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='6gDbriiW1ULWkGfECCkwkcPj8-qN10Fy6ykqJpcN6Mjd9DEJeq7vKQ', max_length=40, unique=True),
        ),
    ]
