# Generated by Django 5.0.7 on 2024-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_remove_apikey_created_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='CwXjss_JTG7RRTHhAxI7TMYZ_XEwwpzDOzpbthnTMEXVlQR2hLQidw', max_length=40, unique=True),
        ),
    ]
