# Generated by Django 5.0.7 on 2024-07-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_apikey_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
